# AATB Audio Archive Toolbox
# example configuration file
# rename this file as "aatb_config.ini" in the program directory

[Settings]
InfotextFileExtension = info.txt
CuesheetFileExtension = info.cue

[FilesToDelete]
# keys must be unique
01 = .bak
02 = .BAK

[DirsToDelete]
# keys must be unique
01 = Images

[Macros]
# macro name = expanded arguments
# the macro will be expanded at runtime
-compall = --compress --m4a=all --flac=all --all-reports --m3u-playlist
-delall = -x --wav
-vtag = -v --tag --all --overwrite
